# Generated by Django 5.0.1 on 2024-01-25 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Dosificaciones',
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Patologias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=80)),
                ('costo', models.FloatField(default=0)),
                ('pvp', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.persona')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.persona')),
                ('patologia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Api.patologia')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('persona', 'patologia')},
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.persona')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='RecetasEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_receta', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('no_receta', models.CharField(max_length=100)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.paciente')),
            ],
            options={
                'verbose_name': 'Encabezado Receta',
                'verbose_name_plural': 'Encabezado Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetasDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.recetasenc')),
            ],
            options={
                'verbose_name': 'Detalle Receta',
                'verbose_name_plural': 'Detalles Recetas',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.paciente')),
            ],
            options={
                'verbose_name_plural': 'Diagnosticos',
                'unique_together': {('paciente', 'observacion')},
            },
        ),
    ]
